---
collections:
  - t_systems_mms.letsencrypt
galaxy_info:
  author: t_systems_mms
  description: Issue certificates from Let's Encrypt via dns- or http-challenge.
  license: GPLv3
  min_ansible_version: 2.9
  galaxy_tags:
    - letsencrypt
