---
### global
letsencrypt_use_acme_live_directory: false
# overwrite letsencrypt_conf_dir if you want to use a directory
# which is accessible from all team members to allow running playbook
# independend while using the same data
letsencrypt_conf_dir: "{{ lookup('env','HOME') }}/letsencrypt"
letsencrypt_cert_dir: "{{ letsencrypt_conf_dir }}/certs"
# set packagemanager to use for localhost connections (yum, apt)
letsencrypt_prerequisites_packagemanager: "yum"
# region for s3 bucket when
letsencrypt_s3_config_region: "eu-west-1"
# path for validation via local path at webserver via http challenge
letsencrypt_local_validation_path: "/var/www/html"

### http challenge / dns challenge
acme_staging_directory: "https://acme-staging-v02.api.letsencrypt.org/directory"
acme_live_directory: "https://acme-v02.api.letsencrypt.org/directory"
account_key_path: "{{ letsencrypt_conf_dir }}/letsencrypt_account.pem"
csr_path: "{{ letsencrypt_cert_dir }}/{{ domain.certificate_name }}.csr"
cert_path: "{{ letsencrypt_cert_dir }}/{{ domain.certificate_name }}.pem"
pfx_cert_path: "{{ letsencrypt_cert_dir }}/{{ domain.certificate_name }}.pfx"
intermediate_path: "{{ letsencrypt_cert_dir }}/{{ domain.certificate_name }}_intermediate.pem"
fullchain_path: "{{ letsencrypt_cert_dir }}/{{ domain.certificate_name }}_fullchain.pem"
private_key_path: "{{ letsencrypt_cert_dir }}/{{ domain.certificate_name }}.key"
remaining_days: "30"
