---
- name: Create CSR for certificate
  openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ private_key_path }}"
    email_address: "{{ domain.email_address }}"
    subject_alt_name: "DNS:{{ domain.subject_alt_name | join(',DNS:') }}"
  when:
    - domain.subject_alt_name.top_level is undefined and domain.subject_alt_name.second_level is undefined

- name: Create CSR for certificate
  openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ private_key_path }}"
    email_address: "{{ domain.email_address }}"
    subject_alt_name: "DNS:{{ (domain.subject_alt_name.top_level | default([])) | union(domain.subject_alt_name.second_level | default([])) | join(',DNS:') }}"
  when:
    - domain.subject_alt_name.top_level is defined or domain.subject_alt_name.second_level is defined

- name: Create a challenge for {{ domain.certificate_name }} using a account key file.
  acme_certificate:
    account_key_src: "{{ account_key_path }}"
    account_email: "{{ account_email }}"
    csr: "{{ csr_path }}"
    cert: "{{ cert_path }}"
    challenge: dns-01
    force: "{{ force_renewal | default(false) }}"
    acme_directory: "{{ acme_directory }}"
    acme_version: 2
    terms_agreed: true
    remaining_days: "{{ remaining_days }}"
    validate_certs: "{{ validate_certs | default(true) }}"
  register: challenge

- name: "do dns challenge with provider {{ letsencrypt_dns_provider | default('unspecified') }}"
  include_tasks: "{{ item }}"
  with_first_found:
    - "dns-challenge/{{ letsencrypt_dns_provider | default('') }}.yml"
    - dns-challenge-unknown.yml
  when:
    - letsencrypt_do_dns_challenge | bool