---
- name: install prerequisites on localhost
  delegate_to: localhost
  package:
    name:
      - python-boto3
    state: present
    use: "{{ letsencrypt_prerequisites_packagemanager }}"

- name: Create CSR for certificate
  openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ private_key_path }}"
    email_address: "{{ domain.email_address }}"
    subject_alt_name: "DNS:{{ domain.subject_alt_name | join(',DNS:') }}"

- name: Create a challenge for {{ domain.certificate_name }} using a account key file.
  acme_certificate:
    account_key_src: "{{ account_key_path }}"
    account_email: "{{ account_email }}"
    csr: "{{ csr_path }}"
    cert: "{{ cert_path }}"
    challenge: http-01
    force: "{{ force_renewal | default(false) }}"
    acme_directory: "{{ acme_directory }}"
    acme_version: 2
    terms_agreed: true
    remaining_days: "{{ remaining_days }}"
  register: challenge

- name: do http challenge s3
  include_tasks: http-challenge-s3.yml
  when:
    - letsencrypt_do_http_challenge | bool
    - letsencrypt_http_provider == "s3"

- name: do http challenge local
  include_tasks: http-challenge-local.yml
  when:
    - letsencrypt_do_http_challenge | bool
    - letsencrypt_http_provider == "local"
